version: "3.9"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
services:
  postgres:
    image: postgres:10.3
    container_name: platzi-events-cqrs-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
    ports:
      - "54321:5432"
    command: [ "postgres" ]
    networks:
      default:
        ipv4_address: 172.20.0.2
  nats:
    image: nats-streaming:0.9.2
    container_name: platzi-events-cqrs-nats
    restart: always
    networks:
      default:
        ipv4_address: 172.20.0.3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    restart: always
    environment:
      - "discovery.type=single-node"
    networks:
      default:
        ipv4_address: 172.20.0.4
  feed:
    build: .
    restart: always
    command: feed-service
    depends_on:
      - postgres
      - nats
    ports:
      - 8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: nats:4222
    networks:
      default:
        ipv4_address: 172.20.0.5
  query:
    build: .
    restart: always
    command: query-service
    depends_on:
      - postgres
      - nats
      - elasticsearch
    ports:
      - 8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: nats:4222
      ELASTICSEARCH_ADDRESS: elasticsearch:9200
    networks:
      default:
        ipv4_address: 172.20.0.6
  pusher:
    build: .
    restart: always
    command: pusher-service
    depends_on:
      - nats
    ports:
      - 8080
    environment:
      NATS_ADDRESS: nats:4222
    networks:
      default:
        ipv4_address: 172.20.0.7
